spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.165.213/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=4CXDkUKV6IaFEwUyvqdwapUD
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:glsc7AGbhJ0h9lefU9GAYqPf@172.21.168.94:27017/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true